apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres-gsc
    access: proxy
    url: warehouse:5432
    database: gsc_db
    user: gsc_user
    isDefault: true
    editable: true
    jsonData:
      database: gsc_db
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    secureJsonData:
      password: gsc_pass_secure_2024

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
